Install Dependencies

Sound Device - used for creating a new recording with Colab notebook

Librosa - Used for finding features from audio

Wavio - used for prediction on a new sample

In [ ]:
!python3 -m pip install sounddevice #start with "!" to use terminal in cloud machine

In [ ]:
!pip install librosa

In [ ]:
!pip install wavio

In [ ]:
#imports

import librosa
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive') #this is done in the cloud using Google colab - Drive was used for the audio recordings, so data is imported with this
import glob
from sklearn.preprocessing import StandardScaler

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [69]:
#goes through the data and prints the different recording file names and locations

directory = "/content/drive/My Drive/note_classification_project/data"

arr = np.array([])

for filen in glob.iglob(f'{directory}/*'):
  arr = np.append(arr,str(filen))

arr



array(['/content/drive/My Drive/note_classification_project/data/6E1.m4a',
       '/content/drive/My Drive/note_classification_project/data/6E2.m4a',
       '/content/drive/My Drive/note_classification_project/data/6F1.m4a',
       '/content/drive/My Drive/note_classification_project/data/6F2.m4a',
       '/content/drive/My Drive/note_classification_project/data/6F#1.m4a',
       '/content/drive/My Drive/note_classification_project/data/6F#2.m4a',
       '/content/drive/My Drive/note_classification_project/data/6G1.m4a',
       '/content/drive/My Drive/note_classification_project/data/6G2.m4a',
       '/content/drive/My Drive/note_classification_project/data/5A1.m4a',
       '/content/drive/My Drive/note_classification_project/data/5A2.m4a',
       '/content/drive/My Drive/note_classification_project/data/5Bb1.m4a',
       '/content/drive/My Drive/note_classification_project/data/5Bb2.m4a',
       '/content/drive/My Drive/note_classification_project/data/5B1.m4a',
       '/content/driv

In [ ]:
df = pd.DataFrame(arr,columns=['name'])
df.head()

name
0  /content/drive/My Drive/note_classification_pr...
1  /content/drive/My Drive/note_classification_pr...
2  /content/drive/My Drive/note_classification_pr...
3  /content/drive/My Drive/note_classification_pr...
4  /content/drive/My Drive/note_classification_pr...

In [ ]:
df2 = pd.DataFrame(np.array(["6E","6E","6F","6F","6F#","6F#","6G","6G","5A","5A","5Bb","5Bb","5B","5B","5C","5C","4D","4D","4Eb","4Eb","4E","4E","4F","4F","3G","3G"]),columns=["String_Note"])

In [ ]:
data = pd.concat([df,df2],axis=1)
data.head()

name String_Note
0  /content/drive/My Drive/note_classification_pr...          6E
1  /content/drive/My Drive/note_classification_pr...          6E
2  /content/drive/My Drive/note_classification_pr...          6F
3  /content/drive/My Drive/note_classification_pr...          6F
4  /content/drive/My Drive/note_classification_pr...         6F#

In [ ]:
#feature scaling to make data better

def scale(X):
  scaler = StandardScaler()

  X = scaler.fit_transform(X)

  return X

In [ ]:
#use librosa to find the features given an audio recording

def findFeatures(l):

  y, sr = librosa.load(l)
        
  #extrapolates Mel-frequency cepstral coefficients
  mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
  mfcc=np.mean(mfcc,axis=1)
  mfcc = np.reshape(mfcc,(-1,1))
  mfcc = scale(mfcc)
  
  print(len(mfcc))


  #evaluates the spectrogram
  spectrogram = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=128,fmax=8000)  
  spectrogram = np.mean(spectrogram, axis = 1)
  spectrogram=np.reshape(spectrogram,(-1,1))
  spectrogram = scale(spectrogram)
  
  print(len(spectrogram))


  #chroma
  chroma = librosa.feature.chroma_cens(y=y, sr=sr)
  chroma = np.mean(chroma, axis = 1)
  chroma=np.reshape(chroma,(-1,1))
  chroma = scale(chroma)
  
  print(len(chroma))



  #contrast
  contrast = librosa.feature.spectral_contrast(y=y, sr=sr)
  contrast = np.mean(contrast, axis= 1)
  contrast=np.reshape(contrast,(-1,1))
  contrast = scale(contrast)
  
  print(len(contrast))



  #put into dictionary for use later
  info = [0,0,0,0]

  info[0] = mfcc
  info[1] = spectrogram
  info[2] = chroma
  info[3] = contrast

  info = np.array(info)
  

  print(info)

  return info
  

In [ ]:
samps = []

#get all the features and put them in their respective arrays

for filen in glob.iglob(f'{directory}/*'):
  values = findFeatures(filen)
  samps.append(values)
  

/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4319212 ],
        [ 0.6629867 ],
        [ 0.47557738],
        [ 0.36411443],
        [ 0.29290506],
        [ 0.24590074],
        [ 0.22065665],
        [ 0.20080565],
        [ 0.18814358],
        [ 0.18554449],
        [ 0.18490508],
        [ 0.19747652],
        [ 0.21290481]], dtype=float32)
 array([[-0.10547236],
        [-0.12628299],
        [ 0.3618034 ],
        [ 0.36113814],
        [-0.1128448 ],
        [ 1.2718338 ],
        [10.950615  ],
        [ 1.5429152 ],
        [-0.13338982],
        [ 0.7009304 ],
        [ 0.93619084],
        [-0.11757673],
        [-0.13536209],
        [-0.08327888],
        [-0.13147436],
        [-0.14371754],
        [ 0.17662007],
        [ 0.3000023 ],
        [-0.14338078],
        [-0.13604262],
        [-0.06022831],
        [-0.12355497],
        [-0.14405352],
        [-0.12045447],
        [-0.10575685],
        [-0.14345948],
        [-0.14267308],
        [-0.12345396],
        [-0.1394109 ],
      

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.42352   ],
        [ 0.725065  ],
        [ 0.46853286],
        [ 0.36744308],
        [ 0.29947048],
        [ 0.24781173],
        [ 0.20998183],
        [ 0.18502106],
        [ 0.17203626],
        [ 0.18594822],
        [ 0.19820543],
        [ 0.19001113],
        [ 0.17399287]], dtype=float32)
 array([[-0.10130674],
        [-0.20157519],
        [ 0.46364748],
        [ 0.49292228],
        [-0.13589098],
        [ 0.2962982 ],
        [ 3.2473319 ],
        [ 0.40193406],
        [-0.10675599],
        [ 5.4356284 ],
        [ 7.094235  ],
        [-0.04426541],
        [ 0.45290425],
        [ 5.4951615 ],
        [ 1.1170602 ],
        [-0.21676877],
        [-0.1617312 ],
        [-0.14013651],
        [-0.21869336],
        [-0.21092829],
        [-0.11835594],
        [-0.19472505],
        [-0.2204694 ],
        [-0.1985895 ],
        [-0.17744298],
        [-0.21397422],
        [-0.20843785],
        [ 0.01741789],
        [-0.14327902],
      

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4272015 ],
        [ 0.6821343 ],
        [ 0.49257147],
        [ 0.37889466],
        [ 0.29838255],
        [ 0.2457203 ],
        [ 0.2155573 ],
        [ 0.190004  ],
        [ 0.17940287],
        [ 0.1868229 ],
        [ 0.19036414],
        [ 0.1867363 ],
        [ 0.18061067]], dtype=float32)
 array([[ 6.7410935e-03],
        [-1.4249982e-01],
        [ 2.8162676e-01],
        [ 6.1644828e-01],
        [-6.2072266e-02],
        [ 1.3140088e-01],
        [ 6.9487576e+00],
        [ 5.9964895e+00],
        [-1.3187148e-01],
        [-3.3423349e-03],
        [ 6.0268073e+00],
        [ 1.7073948e+00],
        [-1.8302305e-01],
        [-1.7742845e-01],
        [-1.4454174e-01],
        [-1.8427409e-01],
        [-1.8833682e-01],
        [-1.1249467e-01],
        [-5.5137210e-02],
        [-1.8843488e-01],
        [-1.8944569e-01],
        [-3.3468768e-02],
        [-8.4101178e-02],
        [-1.8990698e-01],
        [-1.8667629e-01],
        [-1.5014699e-01

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4322467 ],
        [ 0.6178644 ],
        [ 0.497557  ],
        [ 0.40676215],
        [ 0.32025084],
        [ 0.25585428],
        [ 0.22643325],
        [ 0.21095045],
        [ 0.19499888],
        [ 0.17951564],
        [ 0.17289792],
        [ 0.17715454],
        [ 0.17200726]], dtype=float32)
 array([[-3.3342920e-02],
        [-1.6943695e-01],
        [ 4.6064413e-01],
        [ 1.1581627e+00],
        [-9.2484035e-02],
        [-4.2819139e-03],
        [ 7.4883628e+00],
        [ 6.3513212e+00],
        [-1.4877665e-01],
        [-2.4194980e-02],
        [ 4.9369822e+00],
        [ 1.3071221e+00],
        [-1.8114039e-01],
        [-1.8036717e-01],
        [-1.7184161e-01],
        [-1.8249829e-01],
        [-1.8329056e-01],
        [-1.6276485e-01],
        [-1.4883715e-01],
        [-1.8374209e-01],
        [-1.8396029e-01],
        [-1.5950614e-01],
        [-1.6867542e-01],
        [-1.8414883e-01],
        [-1.8377161e-01],
        [-1.8002385e-01

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.446582  ],
        [ 0.54565525],
        [ 0.44300288],
        [ 0.3687363 ],
        [ 0.2947968 ],
        [ 0.25241587],
        [ 0.22732529],
        [ 0.21096869],
        [ 0.215016  ],
        [ 0.23098364],
        [ 0.23510896],
        [ 0.22038946],
        [ 0.20218292]], dtype=float32)
 array([[ 0.12522765],
        [-0.13617316],
        [ 1.0221539 ],
        [ 5.520361  ],
        [ 0.61969346],
        [-0.08724397],
        [ 2.2590942 ],
        [ 9.252659  ],
        [ 0.78510064],
        [-0.1359701 ],
        [ 0.12119549],
        [ 1.0422238 ],
        [-0.12154632],
        [-0.17367113],
        [-0.16771686],
        [-0.15246418],
        [-0.17634654],
        [-0.17710875],
        [-0.13180427],
        [-0.07166797],
        [-0.17400753],
        [-0.17863297],
        [-0.15367292],
        [-0.12602821],
        [-0.17804343],
        [-0.1787423 ],
        [-0.17552581],
        [-0.17265588],
        [-0.17784989],
      

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4519107 ],
        [ 0.5166778 ],
        [ 0.40804836],
        [ 0.34239343],
        [ 0.28787506],
        [ 0.2606146 ],
        [ 0.24359207],
        [ 0.23238826],
        [ 0.23377363],
        [ 0.24003214],
        [ 0.23625606],
        [ 0.22936857],
        [ 0.22089094]], dtype=float32)
 array([[ 0.15901108],
        [-0.14397603],
        [ 0.41167212],
        [ 2.5586402 ],
        [ 0.3902672 ],
        [ 0.43761945],
        [ 2.8671784 ],
        [10.233643  ],
        [ 1.2064176 ],
        [ 0.03216019],
        [ 0.30432427],
        [ 1.6972631 ],
        [-0.08414562],
        [-0.17301853],
        [-0.17361537],
        [-0.1730871 ],
        [-0.17341828],
        [-0.16733034],
        [-0.14980474],
        [-0.13105652],
        [-0.16522427],
        [-0.17018451],
        [-0.15186119],
        [-0.12760219],
        [-0.17572941],
        [-0.176561  ],
        [-0.16327873],
        [-0.1534704 ],
        [-0.17544487],
      

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4416986 ],
        [ 0.56798345],
        [ 0.46263683],
        [ 0.37982565],
        [ 0.3110708 ],
        [ 0.26853964],
        [ 0.24550016],
        [ 0.22997403],
        [ 0.21789159],
        [ 0.2059159 ],
        [ 0.1942452 ],
        [ 0.1832674 ],
        [ 0.17484795]], dtype=float32)
 array([[ 1.0208826e-01],
        [-1.4832450e-01],
        [ 3.9929125e-01],
        [ 8.0206728e+00],
        [ 2.4266362e+00],
        [-7.2508231e-02],
        [ 1.2724711e-01],
        [ 6.2250876e+00],
        [ 3.8487201e+00],
        [-7.9789244e-02],
        [-1.7699322e-01],
        [-8.9168385e-02],
        [-5.4580152e-02],
        [-1.8376414e-01],
        [-1.8591662e-01],
        [ 6.8114279e-03],
        [ 3.0120769e-01],
        [-1.7419191e-01],
        [-1.8712585e-01],
        [-1.5885866e-01],
        [-6.4099878e-02],
        [-1.7288978e-01],
        [-1.8712938e-01],
        [-1.8069361e-01],
        [-1.2089546e-01],
        [-1.7107674e-01

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4477448 ],
        [ 0.5107058 ],
        [ 0.43812078],
        [ 0.37830383],
        [ 0.32459643],
        [ 0.28272584],
        [ 0.25540793],
        [ 0.23823261],
        [ 0.23151875],
        [ 0.22175261],
        [ 0.19983475],
        [ 0.18350756],
        [ 0.18303786]], dtype=float32)
 array([[-0.16105434],
        [-0.16830961],
        [ 0.31763992],
        [ 7.8266816 ],
        [ 2.3176148 ],
        [-0.13616544],
        [ 0.11698919],
        [ 6.5692344 ],
        [ 3.7991986 ],
        [-0.08864652],
        [-0.17066249],
        [-0.0536598 ],
        [-0.02448295],
        [-0.17512707],
        [-0.17697755],
        [-0.11419398],
        [-0.02927523],
        [-0.17407751],
        [-0.17757042],
        [-0.17187133],
        [-0.15495108],
        [-0.17526141],
        [-0.1776687 ],
        [-0.17517425],
        [-0.15558949],
        [-0.17287216],
        [-0.17760721],
        [-0.1774894 ],
        [-0.17677695],
      

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4473982 ],
        [ 0.55762094],
        [ 0.43234846],
        [ 0.3441817 ],
        [ 0.27715412],
        [ 0.24662392],
        [ 0.23790634],
        [ 0.23312306],
        [ 0.23227286],
        [ 0.23188108],
        [ 0.22603403],
        [ 0.21757567],
        [ 0.21067609]], dtype=float32)
 array([[ 0.2937078 ],
        [-0.09785807],
        [-0.0127746 ],
        [ 4.4099045 ],
        [ 9.5246725 ],
        [ 0.34227893],
        [-0.055154  ],
        [-0.02210629],
        [ 2.8072436 ],
        [ 2.448878  ],
        [-0.12497348],
        [-0.17683238],
        [-0.11838195],
        [ 0.41805387],
        [-0.0166556 ],
        [-0.1776426 ],
        [-0.1776124 ],
        [-0.17694502],
        [-0.17648606],
        [-0.1780322 ],
        [-0.17802444],
        [-0.17807998],
        [-0.1354552 ],
        [-0.13082746],
        [-0.1781184 ],
        [-0.17819424],
        [-0.17015013],
        [ 0.11144406],
        [-0.07619368],
      

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4496424 ],
        [ 0.5264475 ],
        [ 0.42212787],
        [ 0.35324442],
        [ 0.29739046],
        [ 0.26337552],
        [ 0.24889176],
        [ 0.24111898],
        [ 0.23437013],
        [ 0.23295447],
        [ 0.226237  ],
        [ 0.2110437 ],
        [ 0.19244073]], dtype=float32)
 array([[ 0.2973308 ],
        [-0.09336971],
        [ 0.09149504],
        [ 4.5185356 ],
        [ 9.775321  ],
        [ 0.68248004],
        [ 0.03299287],
        [-0.02613546],
        [ 2.1824744 ],
        [ 1.819664  ],
        [-0.12856363],
        [-0.1668669 ],
        [-0.12166708],
        [ 0.28208506],
        [-0.04841151],
        [-0.17002559],
        [-0.17005888],
        [-0.16994208],
        [-0.16988522],
        [-0.1702075 ],
        [-0.17011783],
        [-0.1703154 ],
        [-0.16140462],
        [-0.16063426],
        [-0.17037874],
        [-0.17040636],
        [-0.16775231],
        [-0.07718491],
        [-0.1376624 ],
      

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4530451 ],
        [ 0.4799126 ],
        [ 0.40856168],
        [ 0.3618218 ],
        [ 0.31455114],
        [ 0.28130236],
        [ 0.25994906],
        [ 0.23841609],
        [ 0.22457445],
        [ 0.22358817],
        [ 0.22385566],
        [ 0.22197233],
        [ 0.2145399 ]], dtype=float32)
 array([[ 4.5152789e-01],
        [-1.2040013e-01],
        [-7.3645920e-02],
        [ 6.7711008e-01],
        [ 5.0021982e+00],
        [ 4.6646357e-01],
        [-1.3460475e-01],
        [-1.2751737e-01],
        [ 1.5236667e+00],
        [ 9.7428980e+00],
        [ 1.3223702e+00],
        [-1.5930404e-01],
        [-1.6227299e-01],
        [-1.3298847e-01],
        [-3.3768499e-03],
        [-1.3976990e-01],
        [-1.6297160e-01],
        [-1.6285197e-01],
        [-1.6216244e-01],
        [-1.5756315e-01],
        [-1.6285488e-01],
        [-1.6373402e-01],
        [-1.6376312e-01],
        [-1.3367920e-01],
        [-9.0877013e-03],
        [-1.4682031e-01

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.448992  ],
        [ 0.52426016],
        [ 0.4325558 ],
        [ 0.3621169 ],
        [ 0.3089455 ],
        [ 0.26138005],
        [ 0.22851117],
        [ 0.21800056],
        [ 0.22213179],
        [ 0.22521967],
        [ 0.22215593],
        [ 0.22058864],
        [ 0.22312582]], dtype=float32)
 array([[-3.0564894e-03],
        [-1.3536081e-01],
        [-1.2618947e-01],
        [ 7.4450111e-01],
        [ 6.3563542e+00],
        [ 6.2734711e-01],
        [-1.5186340e-01],
        [-1.5182750e-01],
        [ 1.2621228e+00],
        [ 8.9578362e+00],
        [ 1.2732438e+00],
        [-1.6019650e-01],
        [-1.6390198e-01],
        [-1.5926301e-01],
        [-1.4014709e-01],
        [-1.6059881e-01],
        [-1.6383870e-01],
        [-1.6298388e-01],
        [-1.5805583e-01],
        [-1.3196112e-01],
        [-1.5949886e-01],
        [-1.6429670e-01],
        [-1.6428642e-01],
        [-1.0137622e-01],
        [ 1.9984317e-01],
        [-1.1777060e-01

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4394972 ],
        [ 0.59344256],
        [ 0.45610732],
        [ 0.37698337],
        [ 0.3200199 ],
        [ 0.26863128],
        [ 0.23482932],
        [ 0.22362117],
        [ 0.2164485 ],
        [ 0.20416884],
        [ 0.1911485 ],
        [ 0.18163744],
        [ 0.17245919]], dtype=float32)
 array([[-0.17614736],
        [-0.15941083],
        [-0.14348045],
        [-0.05192728],
        [ 2.7656634 ],
        [ 1.0966797 ],
        [-0.18148814],
        [-0.17220654],
        [ 0.15055333],
        [ 5.7024736 ],
        [ 8.436531  ],
        [-0.02082231],
        [-0.18819694],
        [-0.189436  ],
        [ 0.6366214 ],
        [ 3.2913747 ],
        [ 0.13536587],
        [-0.1885118 ],
        [-0.1903158 ],
        [-0.19015075],
        [-0.18563277],
        [-0.18922652],
        [-0.19072635],
        [-0.19080897],
        [-0.19055402],
        [-0.16293515],
        [-0.16535185],
        [-0.1906979 ],
        [-0.19085315],
      

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4439068 ],
        [ 0.54153687],
        [ 0.44823182],
        [ 0.38325688],
        [ 0.33185524],
        [ 0.28376904],
        [ 0.2491675 ],
        [ 0.23582073],
        [ 0.22684255],
        [ 0.20394556],
        [ 0.18440995],
        [ 0.17839496],
        [ 0.17667568]], dtype=float32)
 array([[-0.16049449],
        [-0.13194375],
        [-0.13584125],
        [-0.02030056],
        [ 4.381592  ],
        [ 1.810277  ],
        [-0.16991153],
        [-0.16275178],
        [ 0.05953033],
        [ 5.636979  ],
        [ 8.362302  ],
        [-0.01173263],
        [-0.17394458],
        [-0.17443949],
        [-0.02185466],
        [ 0.4685731 ],
        [-0.11293641],
        [-0.17394608],
        [-0.17553586],
        [-0.17415288],
        [-0.16427928],
        [-0.17292655],
        [-0.1758776 ],
        [-0.17589144],
        [-0.1757765 ],
        [-0.16650033],
        [-0.16743794],
        [-0.1758113 ],
        [-0.17586866],
      

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4397926 ],
        [ 0.5856682 ],
        [ 0.46041805],
        [ 0.37037352],
        [ 0.31201288],
        [ 0.2852943 ],
        [ 0.26276103],
        [ 0.23292279],
        [ 0.2038656 ],
        [ 0.17932719],
        [ 0.17469814],
        [ 0.1832072 ],
        [ 0.18924376]], dtype=float32)
 array([[-0.15108283],
        [-0.1559965 ],
        [-0.1530982 ],
        [-0.12793775],
        [ 4.9556613 ],
        [ 7.6921563 ],
        [-0.1549201 ],
        [-0.16822028],
        [-0.11945505],
        [ 0.10206228],
        [ 6.1567883 ],
        [ 1.695944  ],
        [-0.16637129],
        [-0.16924588],
        [-0.170377  ],
        [-0.14558707],
        [-0.06985316],
        [-0.16456117],
        [-0.17157206],
        [-0.17164227],
        [-0.17150012],
        [-0.1602571 ],
        [-0.16348709],
        [-0.17176175],
        [-0.17177069],
        [-0.17168927],
        [-0.16785604],
        [-0.1393999 ],
        [-0.16683199],
      

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4402292 ],
        [ 0.5707779 ],
        [ 0.45894128],
        [ 0.3836186 ],
        [ 0.3278505 ],
        [ 0.2855948 ],
        [ 0.25673342],
        [ 0.23649675],
        [ 0.2108284 ],
        [ 0.18564086],
        [ 0.17624632],
        [ 0.17418262],
        [ 0.17331766]], dtype=float32)
 array([[-0.16543482],
        [-0.1520358 ],
        [-0.14872338],
        [-0.12422763],
        [ 4.1112385 ],
        [ 6.3643575 ],
        [-0.15945214],
        [-0.16895378],
        [-0.10882706],
        [ 0.17889021],
        [ 7.8851366 ],
        [ 2.1969187 ],
        [-0.16678172],
        [-0.17094985],
        [-0.17199941],
        [-0.11315858],
        [ 0.05709587],
        [-0.15932421],
        [-0.17300394],
        [-0.17312911],
        [-0.17270452],
        [-0.1677956 ],
        [-0.1696488 ],
        [-0.17323549],
        [-0.17325231],
        [-0.17320737],
        [-0.17072414],
        [-0.1524976 ],
        [-0.17013319],
      

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4377723 ],
        [ 0.58888495],
        [ 0.4706479 ],
        [ 0.38047114],
        [ 0.31709573],
        [ 0.29152635],
        [ 0.2597106 ],
        [ 0.2234567 ],
        [ 0.20589921],
        [ 0.19129947],
        [ 0.18220848],
        [ 0.1741317 ],
        [ 0.15244   ]], dtype=float32)
 array([[-0.15908574],
        [-0.08221253],
        [-0.04897235],
        [ 0.06810829],
        [ 0.14398323],
        [ 7.345571  ],
        [ 2.7906978 ],
        [-0.17482485],
        [-0.17310224],
        [-0.17106476],
        [-0.15010738],
        [ 4.6141872 ],
        [ 6.414068  ],
        [-0.14880681],
        [-0.17820252],
        [-0.18027376],
        [-0.18034504],
        [-0.16928798],
        [-0.13838515],
        [-0.17782158],
        [-0.1804815 ],
        [-0.18054184],
        [-0.1805947 ],
        [-0.17919195],
        [-0.16606973],
        [-0.1770189 ],
        [-0.18064435],
        [-0.18064156],
        [-0.18063791],
      

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.436425  ],
        [ 0.66027755],
        [ 0.41727313],
        [ 0.33813474],
        [ 0.28178254],
        [ 0.24012469],
        [ 0.23656614],
        [ 0.25984687],
        [ 0.25749514],
        [ 0.205147  ],
        [ 0.16369082],
        [ 0.18043745],
        [ 0.19564891]], dtype=float32)
 array([[-0.17086   ],
        [-0.14436865],
        [-0.0589741 ],
        [ 0.08416434],
        [ 0.09989788],
        [ 7.903398  ],
        [ 2.9610102 ],
        [-0.20071104],
        [-0.19588913],
        [-0.18624459],
        [-0.16441047],
        [ 4.0299096 ],
        [ 5.568375  ],
        [-0.1854049 ],
        [-0.21302107],
        [-0.216002  ],
        [-0.2154345 ],
        [-0.09253296],
        [ 0.24386513],
        [-0.18705186],
        [-0.21536627],
        [-0.21591677],
        [-0.2165355 ],
        [-0.20994994],
        [-0.15168777],
        [-0.20088446],
        [-0.21655002],
        [-0.21643047],
        [-0.21662171],
      

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.438915  ],
        [ 0.6423253 ],
        [ 0.3987563 ],
        [ 0.3133262 ],
        [ 0.2835099 ],
        [ 0.27986345],
        [ 0.27946538],
        [ 0.27016792],
        [ 0.24771392],
        [ 0.21480127],
        [ 0.18545988],
        [ 0.16801466],
        [ 0.15551077]], dtype=float32)
 array([[-1.5354787e-01],
        [-4.6676084e-02],
        [-2.8823050e-02],
        [ 7.6988824e-02],
        [ 6.3196316e-02],
        [ 5.4898443e+00],
        [ 9.4445562e+00],
        [-9.0477683e-02],
        [-1.6120413e-01],
        [-1.5148443e-01],
        [-1.5107477e-01],
        [-1.2668909e-01],
        [ 7.8814435e-01],
        [ 3.2615814e-01],
        [-1.7188175e-01],
        [-1.7621437e-01],
        [-1.7560548e-01],
        [-1.7535885e-01],
        [-1.6642469e-01],
        [-1.2538664e-01],
        [-1.6778791e-01],
        [-1.7577742e-01],
        [-1.7649879e-01],
        [-1.7652094e-01],
        [-1.7642240e-01],
        [-1.6062437e-01

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4433928 ],
        [ 0.57073534],
        [ 0.4439013 ],
        [ 0.36863804],
        [ 0.29043022],
        [ 0.25676954],
        [ 0.25751716],
        [ 0.25371212],
        [ 0.23895784],
        [ 0.21502511],
        [ 0.18933472],
        [ 0.17984758],
        [ 0.17852372]], dtype=float32)
 array([[-1.54183775e-01],
        [-8.54118168e-02],
        [-6.56246096e-02],
        [ 3.80784348e-02],
        [ 4.70730700e-02],
        [ 5.16559982e+00],
        [ 8.88534832e+00],
        [-9.01864916e-02],
        [-1.58106580e-01],
        [-1.44557148e-01],
        [-1.38530076e-01],
        [ 8.43743235e-03],
        [ 3.86151004e+00],
        [ 1.99462891e+00],
        [-1.50747150e-01],
        [-1.73512042e-01],
        [-1.73526749e-01],
        [-1.73762426e-01],
        [-1.17142737e-01],
        [ 1.20276086e-01],
        [-1.31496534e-01],
        [-1.74203128e-01],
        [-1.74993634e-01],
        [-1.75146922e-01],
        [-1.75024703e-01]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.43983   ],
        [ 0.6153856 ],
        [ 0.38226068],
        [ 0.34453988],
        [ 0.33523983],
        [ 0.3065502 ],
        [ 0.2729326 ],
        [ 0.26255065],
        [ 0.23895794],
        [ 0.19472948],
        [ 0.17165504],
        [ 0.16610722],
        [ 0.14892097]], dtype=float32)
 array([[-0.16961998],
        [-0.14315495],
        [-0.14359541],
        [-0.11718654],
        [-0.11572947],
        [ 0.51337266],
        [ 5.1751575 ],
        [ 0.70011383],
        [-0.16034439],
        [-0.16984   ],
        [-0.17193544],
        [-0.17333089],
        [ 0.8286455 ],
        [ 9.466994  ],
        [ 2.3608217 ],
        [-0.1736331 ],
        [-0.17620562],
        [-0.17775863],
        [-0.17881323],
        [-0.17590386],
        [-0.14086951],
        [-0.16551693],
        [-0.17860629],
        [-0.17888173],
        [-0.17895392],
        [-0.17893538],
        [-0.17882021],
        [-0.17679241],
        [-0.17827967],
      

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4394925 ],
        [ 0.6376318 ],
        [ 0.36730722],
        [ 0.3168302 ],
        [ 0.3150374 ],
        [ 0.3019236 ],
        [ 0.28389028],
        [ 0.26569298],
        [ 0.24655214],
        [ 0.2062004 ],
        [ 0.17515333],
        [ 0.17140801],
        [ 0.1518651 ]], dtype=float32)
 array([[-1.70998707e-01],
        [-8.59385431e-02],
        [-7.12091103e-02],
        [-1.12626329e-03],
        [-4.92263883e-02],
        [ 9.56442773e-01],
        [ 8.68727016e+00],
        [ 1.25700927e+00],
        [-1.21886373e-01],
        [-1.77899182e-01],
        [-1.98763400e-01],
        [-1.98037952e-01],
        [ 4.84000683e-01],
        [ 6.16849136e+00],
        [ 1.43084335e+00],
        [-2.00110182e-01],
        [-2.02017218e-01],
        [-2.02144250e-01],
        [-2.03071401e-01],
        [-2.01717913e-01],
        [-1.87029183e-01],
        [-1.97756410e-01],
        [-2.03090146e-01],
        [-2.03194082e-01],
        [-2.03231320e-01]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4300525 ],
        [ 0.72422624],
        [ 0.40878546],
        [ 0.31982523],
        [ 0.27263862],
        [ 0.24077599],
        [ 0.23237483],
        [ 0.23251808],
        [ 0.22174022],
        [ 0.20449711],
        [ 0.19834694],
        [ 0.19377854],
        [ 0.18054509]], dtype=float32)
 array([[-1.77964613e-01],
        [-1.87572017e-02],
        [-3.47390547e-02],
        [ 9.19437259e-02],
        [ 4.59493026e-02],
        [ 6.88217999e-03],
        [ 2.46664977e+00],
        [ 2.08280945e+00],
        [ 9.53695029e-02],
        [-1.40892163e-01],
        [-2.53260761e-01],
        [-2.59974927e-01],
        [-2.58782327e-01],
        [ 1.13413446e-01],
        [ 1.47628212e+00],
        [-3.24979797e-02],
        [-2.50916511e-01],
        [-2.54144192e-01],
        [-2.61257738e-01],
        [-2.61440307e-01],
        [-2.57765442e-01],
        [ 3.02565753e-01],
        [ 1.17071457e-01],
        [-2.58494318e-01],
        [-2.60633737e-01]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4130683 ],
        [ 0.78697526],
        [ 0.484609  ],
        [ 0.35927007],
        [ 0.28202966],
        [ 0.23892553],
        [ 0.21533927],
        [ 0.18287338],
        [ 0.15308997],
        [ 0.14712751],
        [ 0.16786388],
        [ 0.19495076],
        [ 0.20001422]], dtype=float32)
 array([[-1.4379463e-01],
        [-1.6591589e-01],
        [-1.5033290e-01],
        [-1.0053008e-01],
        [-1.2601590e-01],
        [-1.3480704e-01],
        [ 4.0687853e-01],
        [ 3.5859969e-01],
        [ 5.2754357e-02],
        [-8.8655345e-02],
        [-1.8981592e-01],
        [-1.8450198e-01],
        [-1.6093342e-01],
        [ 2.1730986e+00],
        [ 1.0438771e+01],
        [ 1.1904976e+00],
        [-1.6310365e-01],
        [-1.5808794e-01],
        [-1.8992460e-01],
        [-1.9299144e-01],
        [-1.8156472e-01],
        [ 1.6491355e+00],
        [ 1.1181077e+00],
        [-1.8428022e-01],
        [-1.9296545e-01],
        [-1.9348197e-01

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.4526334 ],
        [ 0.5198182 ],
        [ 0.38244185],
        [ 0.32581294],
        [ 0.29973137],
        [ 0.28736806],
        [ 0.26279986],
        [ 0.22896135],
        [ 0.2163036 ],
        [ 0.22711377],
        [ 0.23559801],
        [ 0.2363848 ],
        [ 0.23029955]], dtype=float32)
 array([[-0.17368037],
        [-0.13669169],
        [-0.12694006],
        [-0.10332755],
        [-0.13358544],
        [-0.15919873],
        [-0.03619476],
        [ 5.975498  ],
        [ 4.741115  ],
        [-0.02539046],
        [-0.17657748],
        [-0.17828746],
        [-0.17682768],
        [-0.17266312],
        [-0.1667981 ],
        [ 2.055028  ],
        [ 7.8673596 ],
        [ 0.23737484],
        [-0.17533179],
        [-0.17873128],
        [-0.17816511],
        [-0.17844342],
        [-0.17908497],
        [-0.1692531 ],
        [-0.03483753],
        [-0.12445495],
        [-0.17762063],
        [-0.17892864],
        [-0.17929631],
      

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


13
128
12
7
[array([[-3.453258  ],
        [ 0.5264087 ],
        [ 0.35759047],
        [ 0.31597292],
        [ 0.30060348],
        [ 0.28273848],
        [ 0.2660908 ],
        [ 0.25203437],
        [ 0.23776414],
        [ 0.22255857],
        [ 0.22200544],
        [ 0.23382904],
        [ 0.23566175]], dtype=float32)
 array([[-0.08575912],
        [ 0.08192489],
        [ 0.10954086],
        [ 0.23455673],
        [ 0.09194144],
        [-0.08805253],
        [-0.10512926],
        [ 1.3681768 ],
        [ 2.0989366 ],
        [ 0.4478143 ],
        [-0.14892054],
        [-0.15714088],
        [-0.14912437],
        [-0.16623776],
        [-0.16167973],
        [ 2.9488814 ],
        [10.456768  ],
        [ 0.46097896],
        [-0.15827301],
        [-0.17363189],
        [-0.17127775],
        [-0.17218406],
        [-0.17349838],
        [-0.16841228],
        [-0.11453234],
        [-0.15056515],
        [-0.16882999],
        [-0.17293105],
        [-0.17414546],
      

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.


In [ ]:
samps2 = np.array(samps)
samps2.shape

(26, 4)

In [ ]:
samps2

array([[array([[-3.4319212 ],
               [ 0.6629867 ],
               [ 0.47557738],
               [ 0.36411443],
               [ 0.29290506],
               [ 0.24590074],
               [ 0.22065665],
               [ 0.20080565],
               [ 0.18814358],
               [ 0.18554449],
               [ 0.18490508],
               [ 0.19747652],
               [ 0.21290481]], dtype=float32),
        array([[-0.10547236],
               [-0.12628299],
               [ 0.3618034 ],
               [ 0.36113814],
               [-0.1128448 ],
               [ 1.2718338 ],
               [10.950615  ],
               [ 1.5429152 ],
               [-0.13338982],
               [ 0.7009304 ],
               [ 0.93619084],
               [-0.11757673],
               [-0.13536209],
               [-0.08327888],
               [-0.13147436],
               [-0.14371754],
               [ 0.17662007],
               [ 0.3000023 ],
               [-0.14338078],
               [-0.1360

In [ ]:
mfcc = []
spectro = []
chroma = []
cont = []

for row in range(len(samps2)):
  for column in range(len(samps2)):
    if column == 0:
      #mfcc
      mfcc.append(samps2[row][column])
    if column == 1:
      #spectro
      spectro.append(samps2[row][column])
    if column == 2:
      #chroma
      chroma.append(samps2[row][column])
    if column == 3:
      #cont
      cont.append(samps2[row][column])

In [ ]:
print(len(mfcc),len(spectro),len(chroma),len(cont))

26 26 26 26


In [ ]:
mfcc = np.array(mfcc)
spectro = np.array(spectro)
chroma = np.array(chroma)
cont = np.array(cont)

In [ ]:
print(mfcc.shape,spectro.shape,chroma.shape,cont.shape)

(26, 13, 1) (26, 128, 1) (26, 12, 1) (26, 7, 1)


In [ ]:
new_mfcc =mfcc.copy().reshape(26,13)
new_spectro = spectro.copy().reshape(26,128)
new_chroma = chroma.copy().reshape(26,12)
new_cont = cont.copy().reshape(26,7)

#Machine learning using Random Forest (collection of many decision trees) and generic Neural Network

# Steps:

1. feature scaling for the features
2. Label Encoding the String_note column
3. split into train and test
4. train multiple models and calculate cost
5. check test cost 
6. choose model with lowest train and test cost

In [ ]:
#imports for ML
import sklearn.preprocessing as preprocessing
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.experimental import enable_halving_search_cv
from sklearn.neural_network import MLPClassifier

In [ ]:
#label encode the targets (different notes)

def find_target(X):
  target = df2['String_Note']
  
  le = preprocessing.LabelEncoder()
  target2 = le.fit_transform(target)

  return target2

target = find_target(data)

In [ ]:
target

array([ 9,  9, 10, 10, 11, 11, 12, 12,  5,  5,  7,  7,  6,  6,  8,  8,  1,
        1,  3,  3,  2,  2,  4,  4,  0,  0])

In [ ]:
"""
new_mfcc 
new_spectro
new_chroma
new_cont
"""

'\nnew_mfcc \nnew_spectro\nnew_chroma\nnew_cont\n'

In [ ]:
#mfcc
X_train_mfcc, X_test_mfcc, y_train_mfcc, y_test_mfcc = train_test_split(new_mfcc, target, test_size=0.2, random_state=42)

#spectro
X_train_spectro, X_test_spectro, y_train_spectro, y_test_spectro = train_test_split(new_spectro, target, test_size=0.2, random_state=42)

#chroma
X_train_chroma, X_test_chroma, y_train_chroma, y_test_chroma = train_test_split(new_chroma, target, test_size=0.2, random_state=42)

#cont
X_train_cont, X_test_cont, y_train_cont, y_test_cont = train_test_split(new_cont, target, test_size=0.2, random_state=42)

In [ ]:
#__________________________________

#train model on each feature

In [ ]:
clf_rf_mfcc = RandomForestClassifier(n_estimators= 1, random_state=np.random.RandomState(2))

clf_rf_mfcc.fit(X_train_mfcc,y_train_mfcc)

y_pred_rf_mfcc = clf_rf_mfcc.predict(X_test_mfcc)
acc_rf_mfcc = clf_rf_mfcc.score(X_test_mfcc,y_test_mfcc)
acc_rf_mfcc

0.3333333333333333

In [ ]:
y_pred_rf_mfcc

array([11,  8, 12,  0,  7, 11])

In [ ]:
y_test_mfcc

array([5, 1, 9, 0, 7, 5])

In [ ]:
clf_rf_spectro = RandomForestClassifier(n_estimators= 3, random_state=np.random.RandomState(9))

clf_rf_spectro.fit(X_train_spectro,y_train_spectro)

y_pred_rf_spectro = clf_rf_spectro.predict(X_test_spectro)
acc_rf_spectro = clf_rf_spectro.score(X_test_spectro,y_test_spectro)
acc_rf_spectro

0.3333333333333333

In [ ]:
y_pred_rf_spectro

array([11,  1,  7,  2,  7,  8])

In [ ]:
y_test_spectro

array([5, 1, 9, 0, 7, 5])

In [ ]:
clf_rf_chroma = RandomForestClassifier(n_estimators= 2, random_state=np.random.RandomState(9))

clf_rf_chroma.fit(X_train_chroma,y_train_chroma)

y_pred_rf_chroma = clf_rf_chroma.predict(X_test_chroma)
acc_rf_chroma = clf_rf_chroma.score(X_test_chroma,y_test_chroma)
acc_rf_chroma

0.3333333333333333

In [ ]:
print(y_pred_rf_chroma, y_test_chroma)

[3 1 9 2 6 3] [5 1 9 0 7 5]


In [ ]:
#______________ cont is not good with random forest

In [ ]:
clf_rf_cont = RandomForestClassifier(n_estimators= 25, random_state=np.random.RandomState(1))

clf_rf_cont.fit(X_train_cont,y_train_cont)

y_pred_rf_cont = clf_rf_cont.predict(X_test_cont)
acc_rf_cont = clf_rf_cont.score(X_test_cont,y_test_cont)
acc_rf_cont

0.0

In [ ]:
print(y_pred_rf_cont, y_test_cont)

[ 7  8 10  3 10  7] [5 1 9 0 7 5]


In [ ]:
#neural net

clf_nn = MLPClassifier(solver='lbfgs', alpha=1e-44, hidden_layer_sizes=(2500, 1500), random_state=9,max_iter=20000,activation='identity')

clf_nn.fit(X_train_cont,y_train_cont)

acc_nn = clf_nn.score(X_test_cont,y_test_cont)
acc_nn

0.16666666666666666

#Accuracy can be greatly improved in future iterations by not taking the mean in the "find_features" function. Further work with the data can improve the accuracy and provide a model far better at its job. The use of more complex Neural Networks such as a custom one using Pytorch, Tensorflow, or Keras can also improve the accuracy.

In [ ]:
def findNote(num):
  notes = {9:"6E",10:"6F",11:"6F",11:"6F#",12:"6G",5:"5A",7:"5Bb",6:"5B",8:"5C",1:"4D",3:"4Eb",2:"4E",4:"4F",0:"3G"}
  return notes.get(num)
    
  

In [ ]:
#to create a new prediction

def new_predict(filen,model):

  values = findFeatures(filen)

  mfcc = []
  spectro = []
  chro = []
  cont = []

  mfcc.append(values.get("mfcc"))
  spectro.append(values.get("spectrogram"))
  chro.append(values.get("chroma"))
  cont.append(values.get("contrast"))

  dataset = pd.DataFrame(data=mfcc, columns = ['mfcc'])

  dataset['spectrogram'] = spectro
  dataset['chroma'] = chro
  dataset['contrast'] = cont


  recorded_val = scale(dataset)

  data = recorded_val

  y_pred = model.predict(data)

  print(y_pred)

  note = findNote(y_pred)

  return y_pred, note


In [ ]:
def getNewNote(mode):

  directory = "/content/drive/My Drive/note_classification_project/new_notes"
  for filen in glob.iglob(f'{directory}/*'):
    values = new_predict(filen,mode)

  print(values)
  return values